In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
data = pd.read_csv("insurance_data.csv")

In [4]:
data

age  bought_insurance
0    22                 0
1    25                 0
2    47                 1
3    52                 0
4    46                 1
5    56                 1
6    55                 0
7    60                 1
8    62                 1
9    61                 1
10   18                 0
11   28                 0
12   27                 0
13   29                 0
14   49                 1
15   55                 1
16   25                 1
17   58                 1
18   19                 0
19   18                 0
20   21                 0
21   26                 0
22   40                 1
23   45                 1
24   50                 1
25   54                 1
26   23                 0

In [5]:
from sklearn.model_selection import train_test_split

In [7]:
x = data["age"]

In [8]:
y = data["bought_insurance"]

In [11]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.1, random_state = 0)

In [12]:
x_test

2     47
24    50
14    49
Name: age, dtype: int64

In [14]:
from sklearn.linear_model import LogisticRegression

In [15]:
model = LogisticRegression()

In [31]:
x_train = x_train.to_frame()  

In [36]:
x_test = x_test.to_frame()  

In [32]:
model.fit(x_train, y_train)

LogisticRegression()

In [37]:
model.predict(x_test)

array([1, 1, 1], dtype=int64)

In [38]:
x_test

age
2    47
24   50
14   49

In [41]:
model.score(x_test, y_test)

1.0

In [42]:
model.predict_proba(x_test)

array([[0.31491732, 0.68508268],
       [0.24068629, 0.75931371],
       [0.26405003, 0.73594997]])

In [ ]:
#first one = 0.68% will buy and second one 0.76% and third one

In [58]:
model.predict([[41]])

array([1], dtype=int64)

In [49]:
data

age  bought_insurance
0    22                 0
1    25                 0
2    47                 1
3    52                 0
4    46                 1
5    56                 1
6    55                 0
7    60                 1
8    62                 1
9    61                 1
10   18                 0
11   28                 0
12   27                 0
13   29                 0
14   49                 1
15   55                 1
16   25                 1
17   58                 1
18   19                 0
19   18                 0
20   21                 0
21   26                 0
22   40                 1
23   45                 1
24   50                 1
25   54                 1
26   23                 0

# Exercise 

In [ ]:
dg