In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv("homeprices.csv")

In [3]:
data

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [22]:
data = data.fillna(3.5)

In [23]:
data

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [24]:
data.isnull().sum()

area        0
bedrooms    0
age         0
price       0
dtype: int64

In [41]:
from sklearn.linear_model import LinearRegression

In [42]:
model = LinearRegression()

In [27]:
x = data[["area", "bedrooms", "age"]]

In [28]:
y = data["price"]

In [29]:
model.fit(x, y)

LinearRegression()

In [30]:
model.coef_

array([  119.67905405, 13097.24903475, -4207.28764479])

In [31]:
model.intercept_

256461.14864864887

In [32]:
model.predict([[3000, 3, 40]])

array([486498.55212355])

In [33]:
model.predict (x)

array([522772.68339768, 604777.99227799, 602994.69111969, 600378.86100386,
       767005.30888031, 792070.46332046])

# Exercise

In [12]:
df = pd.read_csv("hiring.csv")

In [13]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [19]:
from sklearn.preprocessing import LabelEncoder

In [27]:
df["experience"] = df["experience"].fillna("zero")

In [28]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [29]:
new_experience = LabelEncoder()

In [30]:
df["experience"] = new_experience.fit_transform(df["experience"])

In [31]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           6                    8.0                           9      50000
1           6                    8.0                           6      45000
2           1                    6.0                           7      60000
3           5                   10.0                          10      65000
4           2                    9.0                           6      70000
5           4                    7.0                          10      62000
6           3                    NaN                           7      72000
7           0                    7.0                           8      80000

In [51]:
x = df[["experience", "test_score(out of 10)", "interview_score(out of 10)"]]

In [52]:
x

experience  test_score(out of 10)  interview_score(out of 10)
0           6                    8.0                           9
1           6                    8.0                           6
2           1                    6.0                           7
3           5                   10.0                          10
4           2                    9.0                           6
5           4                    7.0                          10
6           3                    8.0                           7
7           0                    7.0                           8

In [38]:
y = df["salary($)"]

In [39]:
y

0    50000
1    45000
2    60000
3    65000
4    70000
5    62000
6    72000
7    80000
Name: salary($), dtype: int64

In [47]:
df["test_score(out of 10)"] = df["test_score(out of 10)"].fillna(8.0)

In [49]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           6                    8.0                           9      50000
1           6                    8.0                           6      45000
2           1                    6.0                           7      60000
3           5                   10.0                          10      65000
4           2                    9.0                           6      70000
5           4                    7.0                          10      62000
6           3                    8.0                           7      72000
7           0                    7.0                           8      80000

In [53]:
model.fit(x, y)

LinearRegression()

In [55]:
model.predict([[3, 10, 4]])

array([67034.06952088])