In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv("salaries.csv")

In [3]:
data

company                  job     degree  salary_more_then_100k
0       google      sales executive  bachelors                      0
1       google      sales executive    masters                      0
2       google     business manager  bachelors                      1
3       google     business manager    masters                      1
4       google  computer programmer  bachelors                      0
5       google  computer programmer    masters                      1
6   abc pharma      sales executive    masters                      0
7   abc pharma  computer programmer  bachelors                      0
8   abc pharma     business manager  bachelors                      0
9   abc pharma     business manager    masters                      1
10    facebook      sales executive  bachelors                      1
11    facebook      sales executive    masters                      1
12    facebook     business manager  bachelors                      1
13    facebook     business manager    masters                      1
14    facebook  computer programmer  bachelors                      1
15    facebook  computer programmer    masters                      1

In [5]:
inputs = data.drop(columns= "salary_more_then_100k")

In [24]:
targets = data["salary_more_then_100k"]

In [9]:
from sklearn.preprocessing import LabelEncoder

In [10]:
le_company = LabelEncoder()
le_job = LabelEncoder()
le_degree = LabelEncoder()

In [13]:
data["new_company"] = le_company.fit_transform(data["company"])
data["new_job"] = le_job.fit_transform(data["job"])
data["new_degree"] = le_degree.fit_transform(data["degree"])

In [14]:
data

company                  job     degree  salary_more_then_100k  \
0       google      sales executive  bachelors                      0   
1       google      sales executive    masters                      0   
2       google     business manager  bachelors                      1   
3       google     business manager    masters                      1   
4       google  computer programmer  bachelors                      0   
5       google  computer programmer    masters                      1   
6   abc pharma      sales executive    masters                      0   
7   abc pharma  computer programmer  bachelors                      0   
8   abc pharma     business manager  bachelors                      0   
9   abc pharma     business manager    masters                      1   
10    facebook      sales executive  bachelors                      1   
11    facebook      sales executive    masters                      1   
12    facebook     business manager  bachelors                      1   
13    facebook     business manager    masters                      1   
14    facebook  computer programmer  bachelors                      1   
15    facebook  computer programmer    masters                      1   

    new_company  new_job  new_degree  
0             2        2           0  
1             2        2           1  
2             2        0           0  
3             2        0           1  
4             2        1           0  
5             2        1           1  
6             0        2           1  
7             0        1           0  
8             0        0           0  
9             0        0           1  
10            1        2           0  
11            1        2           1  
12            1        0           0  
13            1        0           1  
14            1        1           0  
15            1        1           1

In [19]:
inputs = data.drop(["company", "job", "degree", "salary_more_then_100k"], axis = "columns")

In [20]:
inputs

new_company  new_job  new_degree
0             2        2           0
1             2        2           1
2             2        0           0
3             2        0           1
4             2        1           0
5             2        1           1
6             0        2           1
7             0        1           0
8             0        0           0
9             0        0           1
10            1        2           0
11            1        2           1
12            1        0           0
13            1        0           1
14            1        1           0
15            1        1           1

In [21]:
from sklearn.tree import DecisionTreeClassifier

In [22]:
model = DecisionTreeClassifier()

In [25]:
model.fit(inputs, targets)

DecisionTreeClassifier()

In [26]:
model.predict(inputs)

array([0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [27]:
model.score(inputs, targets)

1.0

In [32]:
model.predict([[2,2,1]])

array([0], dtype=int64)

In [97]:
df = pd.read_csv("titanic.csv")

In [98]:
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [99]:
df = df.drop(["PassengerId", "Name", "SibSp", "Parch", "Ticket", "Embarked", "Cabin"], axis = 1)

In [100]:
df

Survived  Pclass     Sex   Age     Fare
0           0       3    male  22.0   7.2500
1           1       1  female  38.0  71.2833
2           1       3  female  26.0   7.9250
3           1       1  female  35.0  53.1000
4           0       3    male  35.0   8.0500
..        ...     ...     ...   ...      ...
886         0       2    male  27.0  13.0000
887         1       1  female  19.0  30.0000
888         0       3  female   NaN  23.4500
889         1       1    male  26.0  30.0000
890         0       3    male  32.0   7.7500

[891 rows x 5 columns]

In [101]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
Fare          0
dtype: int64

In [102]:
df["Age"].median()

28.0

In [103]:
df["Age"] = df["Age"].fillna(df["Age"].median())

In [104]:
df

Survived  Pclass     Sex   Age     Fare
0           0       3    male  22.0   7.2500
1           1       1  female  38.0  71.2833
2           1       3  female  26.0   7.9250
3           1       1  female  35.0  53.1000
4           0       3    male  35.0   8.0500
..        ...     ...     ...   ...      ...
886         0       2    male  27.0  13.0000
887         1       1  female  19.0  30.0000
888         0       3  female  28.0  23.4500
889         1       1    male  26.0  30.0000
890         0       3    male  32.0   7.7500

[891 rows x 5 columns]

In [105]:
df.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
Fare        0
dtype: int64

In [106]:
from sklearn.preprocessing import LabelEncoder

In [107]:
le_sex = LabelEncoder()

In [109]:
df["new_sex"] = le_sex.fit_transform(df["Sex"])

In [110]:
df

Survived  Pclass     Sex   Age     Fare  new_sex
0           0       3    male  22.0   7.2500        1
1           1       1  female  38.0  71.2833        0
2           1       3  female  26.0   7.9250        0
3           1       1  female  35.0  53.1000        0
4           0       3    male  35.0   8.0500        1
..        ...     ...     ...   ...      ...      ...
886         0       2    male  27.0  13.0000        1
887         1       1  female  19.0  30.0000        0
888         0       3  female  28.0  23.4500        0
889         1       1    male  26.0  30.0000        1
890         0       3    male  32.0   7.7500        1

[891 rows x 6 columns]

In [112]:
df = df.drop(columns = "Sex")

In [113]:
df

Survived  Pclass   Age     Fare  new_sex
0           0       3  22.0   7.2500        1
1           1       1  38.0  71.2833        0
2           1       3  26.0   7.9250        0
3           1       1  35.0  53.1000        0
4           0       3  35.0   8.0500        1
..        ...     ...   ...      ...      ...
886         0       2  27.0  13.0000        1
887         1       1  19.0  30.0000        0
888         0       3  28.0  23.4500        0
889         1       1  26.0  30.0000        1
890         0       3  32.0   7.7500        1

[891 rows x 5 columns]

In [114]:
from sklearn.model_selection import train_test_split

In [115]:
inputs = df.drop(["Survived"], axis = 1)

In [116]:
targets = df["Survived"]

In [117]:
inputs_train, inputs_test, targets_train, targets_test = train_test_split(inputs, targets, test_size = 0.2, random_state = 0)

In [118]:
inputs_train.shape

(712, 4)

In [119]:
inputs_test.shape

(179, 4)

In [120]:
from sklearn.tree import DecisionTreeClassifier

In [121]:
model = DecisionTreeClassifier()

In [122]:
model.fit(inputs_train, targets_train)

DecisionTreeClassifier()

In [139]:
prediction = model.predict(inputs_test)

In [132]:
inputs

Pclass   Age     Fare  new_sex
0         3  22.0   7.2500        1
1         1  38.0  71.2833        0
2         3  26.0   7.9250        0
3         1  35.0  53.1000        0
4         3  35.0   8.0500        1
..      ...   ...      ...      ...
886       2  27.0  13.0000        1
887       1  19.0  30.0000        0
888       3  28.0  23.4500        0
889       1  26.0  30.0000        1
890       3  32.0   7.7500        1

[891 rows x 4 columns]

In [133]:
model.predict([[1, 38.0, 71.2833, 0]])

array([1], dtype=int64)

In [148]:
combined = pd.DataFrame(dict({"actual": targets_test, "predict": prediction}))

In [149]:
combined

actual  predict
495       0        0
648       0        0
278       0        0
31        1        1
255       1        0
..      ...      ...
780       1        1
837       0        0
215       1        1
833       0        0
372       0        1

[179 rows x 2 columns]

In [135]:
from sklearn.datasets import load_digits

In [136]:
digits = load_digits()

In [138]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

ValueError: Shape of passed values is (4, 2), indices imply (179, 2)